package org.tiny.lib.database.generate;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import org.tiny.lib.database.entity.Article;
import org.tiny.lib.database.entity.Location;

import org.tiny.lib.database.generate.ArticleDao;
import org.tiny.lib.database.generate.LocationDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig articleDaoConfig;
    private final DaoConfig locationDaoConfig;

    private final ArticleDao articleDao;
    private final LocationDao locationDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        articleDaoConfig = daoConfigMap.get(ArticleDao.class).clone();
        articleDaoConfig.initIdentityScope(type);

        locationDaoConfig = daoConfigMap.get(LocationDao.class).clone();
        locationDaoConfig.initIdentityScope(type);

        articleDao = new ArticleDao(articleDaoConfig, this);
        locationDao = new LocationDao(locationDaoConfig, this);

        registerDao(Article.class, articleDao);
        registerDao(Location.class, locationDao);
    }
    
    public void clear() {
        articleDaoConfig.clearIdentityScope();
        locationDaoConfig.clearIdentityScope();
    }

    public ArticleDao getArticleDao() {
        return articleDao;
    }

    public LocationDao getLocationDao() {
        return locationDao;
    }

}
